[package]
name = "varanus-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-version = { path = "../fast-version" }
thiserror = "1"
lazy_static = "1.4.0"
serde = "1.0.136"
